/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Josec
 */
public class SelectAudiovisualType extends javax.swing.JFrame {

    /**
     * Creates new form SelectAudiovisualType
     */
    public SelectAudiovisualType() {
        initComponents();
        buttonGroupAudiovisual.add(jRadioButtonLaptop);
        buttonGroupAudiovisual.add(jRadioButtonProjector);
        buttonGroupAudiovisual.add(jRadioButtonCD);
        buttonGroupAudiovisual.add(jRadioButtonDVD);
        buttonGroupAudiovisual.add(jRadioButtonSpeakers);
        jLabel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAudiovisual = new javax.swing.ButtonGroup();
        jRadioButtonLaptop = new javax.swing.JRadioButton();
        jRadioButtonProjector = new javax.swing.JRadioButton();
        jRadioButtonCD = new javax.swing.JRadioButton();
        jRadioButtonDVD = new javax.swing.JRadioButton();
        jRadioButtonSpeakers = new javax.swing.JRadioButton();
        jButtonAddAudiovisual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jRadioButtonLaptop.setText("Laptop");

        jRadioButtonProjector.setText("Projector");

        jRadioButtonCD.setText("CD");

        jRadioButtonDVD.setText("DVD");

        jRadioButtonSpeakers.setText("Speakers");

        jButtonAddAudiovisual.setText("Select");
        jButtonAddAudiovisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAudiovisualActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("No option selected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonLaptop)
                            .addComponent(jRadioButtonDVD))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSpeakers)
                            .addComponent(jRadioButtonProjector)))
                    .addComponent(jRadioButtonCD)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddAudiovisual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonLaptop)
                    .addComponent(jRadioButtonProjector))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDVD)
                    .addComponent(jRadioButtonSpeakers))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonCD)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddAudiovisual)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddAudiovisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAudiovisualActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonLaptop.isSelected()){
            this.dispose();
            RegisterLaptop registerLaptop=new RegisterLaptop();
            registerLaptop.setVisible(true);
        }
        else if(jRadioButtonSpeakers.isSelected()){
            this.dispose();
            RegisterSpeakers registerSpeakers=new RegisterSpeakers();
            registerSpeakers.setVisible(true);
        }
        else if(jRadioButtonCD.isSelected()){
            this.dispose();
            RegisterCD registerCD=new RegisterCD();
            registerCD.setVisible(true);
        }
        else if(jRadioButtonDVD.isSelected()){
            this.dispose();
            RegisterDVD registerDVD=new RegisterDVD();
            registerDVD.setVisible(true);
        }
        else if(jRadioButtonProjector.isSelected()){
            this.dispose();
            RegisterProjector registerProjector=new RegisterProjector();
            registerProjector.setVisible(true);
        }
        else{
            jLabel1.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAddAudiovisualActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SelectAudiovisualType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SelectAudiovisualType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SelectAudiovisualType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SelectAudiovisualType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SelectAudiovisualType().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAudiovisual;
    private javax.swing.JButton jButtonAddAudiovisual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonCD;
    private javax.swing.JRadioButton jRadioButtonDVD;
    private javax.swing.JRadioButton jRadioButtonLaptop;
    private javax.swing.JRadioButton jRadioButtonProjector;
    private javax.swing.JRadioButton jRadioButtonSpeakers;
    // End of variables declaration//GEN-END:variables
}
